# Generated by Django 3.2.7 on 2021-09-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Your bio", max_length=325, null=True
            ),
        ),
    ]
