# Generated by Django 3.2.7 on 2021-09-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the course.", max_length=100),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(help_text="Number of the course."),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of adding the course."
                    ),
                ),
            ],
        ),
    ]
