# Generated by Django 3.2.7 on 2021-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursesApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="slug",
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="courses",
            name="name",
            field=models.CharField(help_text="Name of the course.", max_length=50),
        ),
    ]
